### ISSUE TITLE
Spurious error messages while installing with anaconda

### ISSUE THREAD

**Issue by 1kastner** [nobodyinperson/python3-netatmo#2]
While I installed the netatmo package, several spurious error messages showed up. In the end it worked out fine and the example which you provided can be executed successfully. Still I felt the urge to execute some tests which are not included because of your setup.py configuration as far as I can see. Could they somehow be added so that I can verify my installation afterwards? Some ideas on that can be found at http://stackoverflow.com/questions/32390705/should-i-include-tests-and-pyc-files-when-building-package-with-setuptools

    (E:\Programme\miniconda) C:\XXX>pip install netatmo
    Collecting netatmo
      Using cached netatmo-0.1.3.tar.gz
      Running setup.py (path:XXXX\\pip-build-jknnl_o8\netatmo\setup.py) egg_info for package netatmo produced metadata for project name unknown. Fix your #egg=netatmo fragments.
    Requirement already satisfied: pandas in e:\programme\miniconda\lib\site-packages (from unknown)
    Requirement already satisfied: numpy in e:\programme\miniconda\lib\site-packages (from unknown)
    Requirement already satisfied: python-dateutil>=2 in e:\programme\miniconda\lib\site-packages (from pandas->unknown)
    Requirement already satisfied: pytz>=2011k in e:\programme\miniconda\lib\site-packages (from pandas->unknown)
    Requirement already satisfied: six>=1.5 in e:\programme\miniconda\lib\site-packages (from python-dateutil>=2->pandas->unknown)
    Building wheels for collected packages: unknown, unknown
      Running setup.py bdist_wheel for unknown ... done
      Stored in directory: C:\XXX\697b79329f264102de77608f8f99eb073dac8883c72de9a39a
      Running setup.py bdist_wheel for unknown ... error
      Complete output from command E:\Programme\miniconda\python.exe -u -c "import setuptools, tokenize;__file__='XXXX\\pip-build-jknnl_o8\\unknown\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d XXXX\\tmpnxp_6_ispip-wheel- --python-tag cp36:
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "E:\Programme\miniconda\lib\tokenize.py", line 452, in open
          buffer = _builtin_open(filename, 'rb')
      FileNotFoundError: [Errno 2] No such file or directory: 'XXXX\\pip-build-jknnl_o8\\unknown\\setup.py'
    
      ----------------------------------------
      Failed building wheel for unknown
      Running setup.py clean for unknown
      Complete output from command E:\Programme\miniconda\python.exe -u -c "import setuptools, tokenize;__file__='XXXX\\pip-build-jknnl_o8\\unknown\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "E:\Programme\miniconda\lib\tokenize.py", line 452, in open
          buffer = _builtin_open(filename, 'rb')
      FileNotFoundError: [Errno 2] No such file or directory: 'XXXX\\pip-build-jknnl_o8\\unknown\\setup.py'
    
      ----------------------------------------
      Failed cleaning build dir for unknown
    Successfully built unknown
    Failed to build unknown
    Installing collected packages: unknown
    Successfully installed unknown-0.1.3

**Comment by nobodyinperson** [comment]
Connected to #1. Should be fixed as of  9ac3f90. There is a new version v0.1.4 on PyPi.

**Comment by 1kastner** [comment]
Again everything has been solved!
