### ISSUE TITLE
Getpublicdata

### ISSUE THREAD

**Issue by sunithak** [nobodyinperson/python3-netatmo#5]
Hello,
I am new to programming. I would like to retrieve getpublicdata by using this API. I am creating a new file and executing the example.py with my credentials. But it is showing some errors. with auth and request page. I updated my credentials. I imported whole project into my eclipse. I am little confused which file to run for only getpublicdata. I would like to get the data into json file. Could you please help me. Thank you.

**Comment by nobodyinperson** [comment]
Hey,

First you need to install this `netatmo` Python package properly. As explained in the README, this is best done by

```bash
pip install --user netatmo
```

If you are on Windows, I don't know how exactly you get `pip`. You might want to google that.

Then you need to copy the example script from the README into a file called `example.py`:

```python
import netatmo

# your netatmo connect developer credentials
credentials = {
    "password":"5uP3rP45sW0rD",
    "username":"user.email@internet.com",
    "client_id":    "03012823b3fd2e420fbf980b",
    "client_secret":"YXNkZmFzZGYgamFzamYgbGFzIG"
}

# configure the authentication
authentication = netatmo.api.authentication.Authentication(
    credentials=credentials,
    tmpfile = "temp_auth.json"
)
# providing a path to a tmpfile is optionally.
# If you do so, the tokens are stored there for later reuse, 
# e.g. next time you invoke this script.
# This saves time because no new tokens have to be requested.
# New tokens are then only requested if the old ones expire.

# create a api client
client = netatmo.api.client.NetatmoClient(authentication)

# lat/lon outline of Hamburg/Germany
hamburg_region = {
    "lat_ne" : 53.7499,
    "lat_sw" : 53.3809,
    "lon_ne" : 10.3471,
    "lon_sw" : 9.7085,
}

# issue the API request
hamburg = client.Getpublicdata(region = hamburg_region)

# convert the response to a pandas.DataFrame
print(hamburg.dataframe())
```

Then you have to adjust your credentials at the top (you get them from your netatmo connect developer account).

Then you execute the script `example.py`. I don't know how to do that exactly on Windows. But on Linux you open a Terminal in the folder of the `example.py` and execute

```bash
python3 example.py
```

This should print something like

```
     index   altitude  humidity                 id   latitude  longitude  \
0        0  30.000000        84  70:ee:50:12:9a:b8  53.516950  10.155990
1        1  23.000000        83  70:ee:50:03:da:4c  53.523361  10.167193
2        2  23.000000        76  70:ee:50:01:47:34  53.510080  10.165600
3        3  15.000000        93  70:ee:50:03:bc:2c  53.530948  10.134062
..     ...        ...       ...                ...        ...        ...

     pressure  temperature       time_humidity       time_pressure  \
0      1029.1          8.1 2017-02-16 10:59:31 2017-02-16 11:00:05
1      1026.7          8.3 2017-02-16 10:53:53 2017-02-16 10:54:01
2      1030.0          9.4 2017-02-16 10:53:06 2017-02-16 10:53:42
3      1026.8          8.0 2017-02-16 10:56:32 2017-02-16 10:56:54
..        ...          ...                 ...                 ...

       time_temperature       timezone
0   2017-02-16 10:59:31  Europe/Berlin
1   2017-02-16 10:53:53  Europe/Berlin
2   2017-02-16 10:53:06  Europe/Berlin
3   2017-02-16 10:56:32  Europe/Berlin
..                  ...            ...

[708 rows x 12 columns]
```

At the end of the script, you have the `hamburg` variable. You can get the actual JSON response of the Netatmo API by `hamburg.response`. This JSON is a little convolved and you might prefer to convert the API response to a pandas dataframe by `hamburg.dataframe` for ease of use.

For Windows questions, @1kastner surely has some tips for you.

**Comment by 1kastner** [comment]
Well, on Windows everything works pretty much the same. Instead of a terminal it is the command line, but the commands you run do not differ. Check out the pandas DataFrame class (google "pandas documentation" for that). It offers methods to directly export the dataframe at hand and save it as e.g. csv.

**Comment by 1kastner** [comment]
@sunithak please create a gist of your exact script and link it here (with the error messages you get). Otherwise no more help can be done as your description is rather vague - especially I have never used Eclipse for Python. Maybe you can start to use the command line because then it is easy to understand for us what you are doing and where you struggle.

**Comment by sunithak** [comment]
Thank you very much for the response. I thought python 2 and python3 are creating problem. I removed python2 from system. Whole desktop disappeared. I am sorry for the late reply. 
![screenshot from 2017-06-01 15-41-53](https://cloud.githubusercontent.com/assets/7197392/26682555/22c0ffde-46e1-11e7-9e3e-679a5b9885c8.png)
I am attaching the screenshot of the error i am getting. netatmo is not importing. When i run pip install --user netatmo.. It is showing Requirements already satisfied. Please check and let me know. Thank you again for the help.

**Comment by sunithak** [comment]
Hello,
I am sorry for the trouble. It was problem with pip. I got the output. Thank you very much for the help.

**Comment by nobodyinperson** [comment]
No problem ;-)

It was actually my mistake... You see from the `Requirement already satisfied`-message, that your `pip install --user netatmo` installed the `netatmo`-module for **Python 2**. You want to install it for **Python 3**, because you execute your `Example.py` with `python3.5`. I am actually not sure why it is possible to install this package for Python 2 anyway...
So, to install `netatmo` for **Python 3**, you will want to use `pip3` instead :-)

```bash
pip3 install --user netatmo
```

Then you should finally be able to use it :-D

**Comment by nobodyinperson** [comment]
If your problem is solved, you are encouraged to close this issue ;-)
